public/index.html, src/components/Modal/Modal.jsx, src/components/Modal/Modal.styled.js
=> modal_portal

src/components/Navigation/Navigation.jsx, src/components/Navigation/Navigation.styled.js
1) поки немає routes  то замість NavLink поставила тимчасово тег a, щоб не вибивало помилку
2) замість іконок заглушка
3) не знайшла ще шрифти , потрібно буде додати
=> styles for navigation

src/components/Header/Header.jsx, src/components/Header/Header.styled.js
add Header components and styles
=> add Header and styles

src/HOC/PublicRoute/PublicRoute.jsx, src/components/App.jsx, src/components/Layout/Layout.jsx, src/index.js, src/pages/RegistrationPage/RegistrationPage.jsx
=> layout+routes

src/components/RegisrationForm/RegisrationForm.jsx
RegistrationForm with formik / yup
=> formik-yup

src/pages/LoginPage/LoginPage.styled.js, src/pages/RegistrationPage/RegistrationPage.styled.js, src/redux/TransactionCategories/categoriesSlice.js, src/redux/TransactionCategories/operations.js, src/redux/store.js
=> add_tranzCategories_slice

package-lock.json, package.json, src/components/Header/Header.styled.js, src/components/ModalAddTransaction/ModalAddTransaction.jsx, src/components/ModalAddTransaction/ModalAddTransaction.styled.js, src/components/ModalAddTransaction/Switcher.jsx, src/components/ModalAddTransaction/Switcher.styled.js
- форма (не готовий перемикач)
- дататаймер(зробила без стилізації, зробила щоб не вибиралась майбутня дата)
=> add datatimer and modal add trans

src/components/App.jsx, src/components/Header/Header.styled.js, src/pages/NotFound/NotFound.jsx, src/pages/NotFound/NotFound.styled.js
Зробила сторінку 404, підключила в АРР
=> add NotFoundPage

src/components/Header/Header.jsx, src/components/Header/Header.styled.js
=> add onClick (exept logoutthunk)

src/components/Header/Header.styled.js, src/components/ModalAddTransaction/ModalAddTransaction.jsx, src/components/ModalAddTransaction/ModalAddTransaction.styled.js, src/index.js, src/styles/Button.js, src/styles/GlobalStyle.js
=> datatimer updated

src/components/App.jsx
=> transfer Not Found Page into the main Routes

src/components/ModalAddTransaction/ModalAddTransaction.jsx, src/components/ModalAddTransaction/ModalAddTransaction.styled.js, src/components/ModalAddTransaction/Switcher.jsx, src/components/ModalAddTransaction/Switcher.styled.js
=> add toggle

src/components/RegisrationForm/RegisrationForm.jsx, src/components/RegisrationForm/RegisrationForm.styled.js
=> RegistrationForm

src/components/ModalAddTransaction/ModalAddTransaction.jsx, src/components/ModalAddTransaction/ModalAddTransaction.styled.js, src/components/ModalAddTransaction/Select.jsx, src/components/ModalAddTransaction/Switcher.jsx, src/redux/TransactionCategories/categoriesSlice.js, src/redux/TransactionCategories/selectors.js, src/styles/GlobalStyle.js
=> add select options

src/components/Header/Header.jsx, src/components/ModalAddTransaction/ModalAddTransaction.jsx, src/components/ModalAddTransaction/ModalAddTransaction.styled.js
=> add trans add thunk

src/components/TransactionsList/TransactionsList.jsx, src/components/TransactionsList/TransactionsList.styled.js
1) я змінила розмітку , щоб таблиця mapилась
2) я не розібралася з даними і не знайшла як їх витянути transactions тому створила тестовий масив transactions щоб відобразити
=> Changed transactionList

src/components/Header/Header.jsx, src/components/Header/Header.styled.js
=> updated Logo Link

src/components/ModalAddTransaction/Select.jsx, src/pictures/SpriteSVG.jsx
=> fixed svg err

src/components/Header/Header.styled.js, src/components/ModalAddTransaction/ModalAddTransaction.styled.js, src/components/ModalAddTransaction/Select.styled.js
=> updated styles

src/components/ButtonAddTransactions/ButtonAddTransactions.styled.js
=> add btn styled

src/components/TransactionsList/TransactionListMobile.jsx, src/components/TransactionsList/TransactionListMobile.styled.js
1) потрібно буде змінити бекграун , тому що я так розумію він прозорий і фон дає колір, оскільки фону немає, то я зробила просто фіолетовий, щоб було видно табличку) 
2) я ніяку логіку не прописувала, тому що ви там щось змінюєте в самому TransactionList щ, тому щоб не переписувати , я просто зробила через map
=> TransactionList Mobile

src/components/DiagramTab/DiagramTab.styled.js
Трошки почистила стилі для селекта, там дещо було зайве то я видалила, змінювала тільки файл стилів нікуди більше не лізла
=> styles for diagram tab

src/components/ModalAddTransaction/ModalAddTransaction.jsx, src/components/ModalAddTransaction/ModalAddTransaction.styled.js, src/components/ModalAddTransaction/Select.styled.js
=> updated form add trans

src/components/Main/Main.styled.js
=> onGradient+++

src/components/Navigation/Navigation.styled.js
=> updated icons nav

src/components/Header/Header.styled.js
=> updated hover

src/components/Table/Table.jsx
=> round|_num

src/components/Navigation/Navigation.jsx, src/components/Navigation/Navigation.styled.js
=> navigation updated styles adaptive

src/components/TransactionsList/TransactionsList.jsx
=> updated data format

src/components/TransactionsList/TransactionsList.jsx
=> updated for tablet

src/pages/NotFound/NotFound.jsx, src/pages/NotFound/NotFound.styled.js
трошки змінила стилі на нот-фаунд
=> updated page not found

src/components/RegisrationForm/RegisrationForm.jsx, src/components/RegisrationForm/RegisrationForm.styled.js
Уведомления от formik теперь стоят на своём месте
=> registration-form

src/components/ModalAddTransaction/ModalAddTransaction.jsx, src/components/ModalAddTransaction/ModalAddTransaction.styled.js
додала помилку на інпут через яп
=> add yup err message

src/components/Currency/Currency.styled.js
=> change_styled

src/components/Balance/Balance.jsx, src/components/Balance/Balance.styled.js
=> balance_new
